version: '3'

services:
  api:
    build: . 
    container_name: dans_nlp_toolbox
    ports:
      # The HTTP port
      - "8099:80"
      - "8098:8080"
    environment:
      - DEBUG_DISABLE=${DEBUG_DISABLE}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - THISAPI=${THISAPI}
      - CACHEFOLDER=${CACHEFOLDER}
      - DOCCANO_URL=${DOCCANO_URL}
      - DOCCANO_USER=${DOCCANO_USER}
      - DOCCANO_PROJECT_ID=${DOCCANO_PROJECT_ID}
      - DOCCANO_PASSWORD=${DOCCANO_PASSWORD}
      - TASKNAME=${TASKNAME}
      #- disable_nlp=${disable_nlp}
    volumes:
      - ./data:/tmp
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
