version: '3'

services:
  api:
    build: . 
    container_name: dans_nlp_toolbox
    ports:
      # The HTTP port
      - "8091:80"
      - "8093:8080"
    environment:
      - DEBUG_DISABLE=False
      - DEBUG_LEVEL=INFO
      - THISAPI=http://192.168.1.101:8091
      - CACHEFOLDER=/tmp
      - DOCCANO_URL=http://192.168.1.101:3000
      - DOCCANO_USER=admin
      - DOCCANO_PASSWORD=password
      #- disable_nlp=True
    volumes:
      - ./data:/tmp
